### ISSUE TITLE
 Specified for property 'bundle' does not exist.

### ISSUE THREAD

**Issue by samk17cmutpm** [shiguredo/sora-android-sdk-quickstart#1]
Hi, I just cloned this sample but I cannot run it.
Here the message from console message
![sora](https://user-images.githubusercontent.com/7029528/30043693-2f159c62-9223-11e7-8ec4-beba17a9d003.png)
Please help me to solve the problem, Thanks 
 File '/home/sam_nguyen/sora-android-sdk-quickstart/libwebrtc/libwebrtc.aar' specified for property 'bundle' does not exist.

**Comment by shino** [comment]
Hi @samk17cmutpm ,

Thanks for reporting an issue, but I'm sorry that Shiguredo Inc. provides support only in Japanese.
I recommend you to read the doc https://sora.shiguredo.jp/android-sdk-doc/index.html to
try the quickstart application. Then, please read guideline for submitting issues: https://github.com/shiguredo/sora-android-sdk/blob/develop/docs/CONTRIBUTING.md and fill out issue template:

```
## サマリ

<!--
この issue の簡潔な説明を書いてください。
-->

## 環境

- Android 端末の Android バージョン: 
- Android 端末の型番: 
- WebRTC SFU Sora バージョン: 
- Sora Android SDK の AAR バージョン: 
- libwebrtc の 時雨堂ビルド AAR バージョン: 
- Android Studio バージョン: 
- その他、関連する環境情報: 

## 期待する動作、現象

<!--
ビルドが実行され foo.aar ファイルが生成される、映像が画面に表示されるなど、
あなたが期待することを記してください。
-->

## 実際の動作、現象

<!--
実際に起きたことを記してください。ビルドであれば実行コマンドとログ、
アプリケーション実行中であればスクリーンショットや logcat 出力など。
期待する動作にならなかった時間帯の Sora サーバ側のログも有用です。
-->

## 再現手順

<!--
実行したコマンドやアプリケーションの操作手順を記してください。
ビルドスクリプト、ソースコードを含むミニマルな再現サンプルがあると
やりとりがスムーズになります。
-->

## 実現したいこと

<!--
この issue の解決に限らず、実現したいことを可能な範囲で記述してください。
-->

## その他

<!--
あなたの調査でわかったこと、関連する情報など。
-->


```

After this comment, I'm going to write further comments in Japanese.
Thanks again!

**Comment by samk17cmutpm** [comment]
Hi, thanks for your soon response 
I downloaded libwebrtc.aar and sora-android-sdk-release.aar files then I put them into libwebrtc and sora-android-sdk folders. Now it works, thanks for your supporting
